//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELjournal.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int idJournal { get; set; }
        public int idStudent { get; set; }
        public int mark { get; set; }
        public int idSubj { get; set; }
        public System.DateTime dateM { get; set; }
        public int idTeach { get; set; }
        public string comment { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
